In [2]:
import imblearn
import pandas as pd
import numpy as np
import weka.core.jvm as jvm
from weka.classifiers import Classifier
from weka.core.converters import Loader, Saver
from weka.classifiers import Classifier, Evaluation
from weka.core.classes import Random
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn import metrics
from sklearn.model_selection import KFold
jvm.start()
jvm.start(packages=True)

X = np.array([[0,1,2,1,0],[0,1,1,1,1],[1,1,1,1,1],[0,1,2,1,0],[0,1,1,1,1],[1,1,1,1,1],[0,1,2,1,0],[0,1,1,1,1],[1,1,1,1,1],[0,1,2,1,0],[0,1,1,1,1],[1,1,1,1,1]])
X = pd.DataFrame(X,columns=['a','b','c','d','e'])
print(X)


DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['C:\\Users\\DHRUV\\anaconda3\\lib\\site-packages\\javabridge\\jars\\rhino-1.7R4.jar', 'C:\\Users\\DHRUV\\anaconda3\\lib\\site-packages\\javabridge\\jars\\runnablequeue.jar', 'C:\\Users\\DHRUV\\anaconda3\\lib\\site-packages\\javabridge\\jars\\cpython.jar', 'C:\\Users\\DHRUV\\anaconda3\\lib\\site-packages\\weka\\lib\\python-weka-wrapper.jar', 'C:\\Users\\DHRUV\\anaconda3\\lib\\site-packages\\weka\\lib\\weka.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support disabled
INFO:weka.core.jvm:JVM already running, call jvm.stop() first


    a  b  c  d  e
0   0  1  2  1  0
1   0  1  1  1  1
2   1  1  1  1  1
3   0  1  2  1  0
4   0  1  1  1  1
5   1  1  1  1  1
6   0  1  2  1  0
7   0  1  1  1  1
8   1  1  1  1  1
9   0  1  2  1  0
10  0  1  1  1  1
11  1  1  1  1  1


In [3]:
y = np.array([0,0,0,0,0,0,0,0,0,1,1,1])
y = pd.DataFrame(y,columns=['O'])
print(y)


    O
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   1
10  1
11  1


In [4]:
from imblearn.over_sampling import SMOTE 
oversample = SMOTE(k_neighbors = 2)
X, y = oversample.fit_resample(X, y)
print(X)
print(y)

    a  b  c  d  e
0   0  1  2  1  0
1   0  1  1  1  1
2   1  1  1  1  1
3   0  1  2  1  0
4   0  1  1  1  1
5   1  1  1  1  1
6   0  1  2  1  0
7   0  1  1  1  1
8   1  1  1  1  1
9   0  1  2  1  0
10  0  1  1  1  1
11  1  1  1  1  1
12  0  1  1  1  0
13  0  1  1  1  0
14  0  1  1  1  0
15  0  1  1  1  1
16  0  1  1  1  1
17  0  1  1  1  0
    O
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   1
10  1
11  1
12  1
13  1
14  1
15  1
16  1
17  1


In [5]:
print(X.shape[0])

18


In [6]:
y1 = y.iloc[:,0]
print(y1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
Name: O, dtype: int32


In [7]:
"""
print(y1.shape[0])

for i in np.arange(0,18):
    if y1[i] == 0:
        y1[i] = 'neg'
    else:
        y1[i] = 'pos'

print(y1)
"""

"\nprint(y1.shape[0])\n\nfor i in np.arange(0,18):\n    if y1[i] == 0:\n        y1[i] = 'neg'\n    else:\n        y1[i] = 'pos'\n\nprint(y1)\n"

In [8]:
#df = pd.concat([X, y1], axis=1)
#print(df)

In [9]:
from weka.core.dataset import create_instances_from_lists
from weka.core.dataset import create_instances_from_matrices
X1 = X.to_numpy()

print(X1)

[[0 1 2 1 0]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 2 1 0]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 2 1 0]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 2 1 0]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 0]]


In [15]:
from weka.filters import Filter
data = create_instances_from_matrices(X1,y1)

print(data)

data.attribute_names()

discretize_data = Filter(classname = 'weka.filters.unsupervised.attribute.NumericToNominal', options = ['-R', 'last'])

discretize_data.inputformat(data)
discretized = discretize_data.filter(data)

print(discretized)



@relation data

@attribute x1 numeric
@attribute x2 numeric
@attribute x3 numeric
@attribute x4 numeric
@attribute x5 numeric
@attribute y numeric

@data
0,1,2,1,0,0
0,1,1,1,1,0
1,1,1,1,1,0
0,1,2,1,0,0
0,1,1,1,1,0
1,1,1,1,1,0
0,1,2,1,0,0
0,1,1,1,1,0
1,1,1,1,1,0
0,1,2,1,0,1
0,1,1,1,1,1
1,1,1,1,1,1
0,1,1,1,0,1
0,1,1,1,0,1
0,1,1,1,0,1
0,1,1,1,1,1
0,1,1,1,1,1
0,1,1,1,0,1
@relation data-weka.filters.unsupervised.attribute.NumericToNominal-Rlast

@attribute x1 numeric
@attribute x2 numeric
@attribute x3 numeric
@attribute x4 numeric
@attribute x5 numeric
@attribute y {0,1}

@data
0,1,2,1,0,0
0,1,1,1,1,0
1,1,1,1,1,0
0,1,2,1,0,0
0,1,1,1,1,0
1,1,1,1,1,0
0,1,2,1,0,0
0,1,1,1,1,0
1,1,1,1,1,0
0,1,2,1,0,1
0,1,1,1,1,1
1,1,1,1,1,1
0,1,1,1,0,1
0,1,1,1,0,1
0,1,1,1,0,1
0,1,1,1,1,1
0,1,1,1,1,1
0,1,1,1,0,1


In [17]:
classifier = Classifier(classname="weka.classifiers.trees.LMT")
discretized.class_is_last()
classifier.build_classifier(discretized)